### ISSUE TITLE
Weekly Scrum - 3/14/2018

### ISSUE THREAD

**Issue by omaribrahim4** [raymondwu1/SYSC4806Project#21]
what have I done this week?
what will I do next week?
what is holding me back? (optional)

**Comment by DanHoganRed** [comment]
what have I done this week?
Mostly refactoring, bug fixes and tests. 
what will I do next week?
Make the table better so you can see the full perk info 
what is holding me back? 
Omar adding upvote functionality

**Comment by raymondwu1** [comment]
what have I done this week?
Added subscription repo, changed how we add perks and subscriptions, added controller tests 
what will I do next week?
Add search functionality
what is holding me back? (optional)

**Comment by Soluzochukwu** [comment]
What have I done this week?
- Created error pages & forgot Password
- Wrote tests for forgot Password

What will I do next week?
- Modify the error pages to be dynamic using JavaScript

What is holding me back?
- Lack of javascript knowledge
- Nothing

**Comment by omaribrahim4** [comment]
What have I done this week?
    Added Upvote & Downvote Buttons
    Added Upvote & Downvote Controllers & Functionality

What will I do next week?
    Add limitations to perks based on geographic area and in time (Might change)

What is holding me back?
    Nothing
