### ISSUE TITLE
Weekly Scrum - 04/01/2018

### ISSUE THREAD

**Issue by DanHoganRed** [raymondwu1/SYSC4806Project#53]
what have I done this week?
what will I do next week?
what is holding me back? (optional)

**Comment by DanHoganRed** [comment]
what have I done this week?
Add columns to the perk table
what will I do next week?
Allow signed in users to see all subscriptions as well
what is holding me back? 
The main page table being made. It will have all subscriptions so I'd like to reuse the code.

**Comment by Soluzochukwu** [comment]
what have I done this week?
- Added table to home page (for users without profiles)
- Populated table with all available subscriptions
- Wrote test for the required Ajax Controller methods

**Comment by raymondwu1** [comment]
what have I done this week?
Added a search bar on the home page and user page
Added ability to sort table based on expiration date
Fixed some bugs

**Comment by omaribrahim4** [comment]
What have I done this week?
Added Upvote/Downvote functionality + buttons
Sort table by votes
Limit each user to one upvote/downvote
