### ISSUE TITLE
Weekly Scrum - 3/7/2018

### ISSUE THREAD

**Issue by raymondwu1** [raymondwu1/SYSC4806Project#7]
- what have I done this week?
User registration and sign in and spring mvc tests
- what will I do next week?
Search for perks based on upvote and downvotes and expiration date
- what is holding me back? (optional)
Nothing

**Comment by Soluzochukwu** [comment]
what have I done this week?
  

- Developed basic html pages to get the project kick started

what will I do next week?
   

- Add java script functionalities to improve our html pages (other tasks may follow) 

what is holding me back? (optional)
   

-  Current lack of knowledge. But don't worry i'll get there

**Comment by omaribrahim4** [comment]
- What have I done this week?
   Unit Test & UML Class Diagrams
- What will I do next week?
    Add upvote/downvote functionality
- What is holding me back? (optional)

**Comment by DanHoganRed** [comment]
- What have I done this week?
Added entities, popups, created ajax requests and created ajax restcontroller.

- What will I do next week?
Refactor and Test
